# Generated by Django 6.1 on 2026-08-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_book', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketbook',
            name='card',
            field=models.CharField(max_length=16, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='basketbook',
            name='choice_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='basketbook',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='basketbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='basketbook',
            name='name_order',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='basketbook',
            name='status',
            field=models.CharField(default='В обработке', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='basketbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
