# Generated by Django 6.1 on 2026-08-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='book/')),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('url_blog', models.URLField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
