# Generated by Django 6.1 on 2026-08-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название локации')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес локации')),
                ('categories', models.ManyToManyField(null=True, to='horse_tour.horsecategory')),
            ],
            options={
                'verbose_name': 'Локацию',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('text', models.CharField(max_length=500, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.tourlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка лошади')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horse_tour.horsecategory')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.tourlocation')),
            ],
        ),
    ]
