# Generated by Django 6.1 on 2026-08-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourlocation',
            name='categories',
        ),
        migrations.AddField(
            model_name='tourlocation',
            name='suitable_horse_types',
            field=models.ManyToManyField(to='horse_tour.horsecategory'),
        ),
    ]
